:_module-type: PROCEDURE
[id="creating-new-aspect-tuned-profiles_{context}"]
= Creating new Aspect-TuneD profiles

[role="_abstract"]
This procedure creates a new *Aspect-TuneD* profile with custom performance rules.

.Prerequisites

ifndef::pantheonenv[]
* The `aspect-tuned` service is running. See xref:installing-and-enabling-aspect-tuned_getting-started-with-aspect-tuned[Installing and Enabling Aspect-TuneD] for details.
endif::[]

ifdef::pantheonenv[]
* The `aspect-tuned` service is running. See xref:modules/performance/proc_installing-and-enabling-aspect-tuned.adoc[Installing and Enabling Aspect-TuneD] for details.
endif::[]

.Procedure

. In the [filename]`/etc/aspect-tuned/profiles/` directory, create a new directory named the same as the profile that you want to create:
+
[subs="quotes"]
----
# mkdir /etc/aspect-tuned/profiles/[replaceable]_my-profile_
----

. In the new directory, create a file named [filename]`aspect-tuned.conf`. Add a `[main]` section and plug-in definitions in it, according to your requirements.
+
For example, see the configuration of the `balanced` profile:
+
----
[main]
summary=General non-specialized Aspect-TuneD profile

[cpu]
governor=conservative
energy_perf_bias=normal

[audio]
timeout=10

[video]
radeon_powersave=dpm-balanced, auto

[scsi_host]
alpm=medium_power
----

. To activate the profile, use:
+
[subs="quotes"]
----
# aspect-tuned-adm profile [replaceable]_my-profile_
----

. Verify that the *Aspect-TuneD* profile is active and the system settings are applied:
+
[subs="quotes"]
----
$ aspect-tuned-adm active

Current active profile: [replaceable]_my-profile_
----
+
----
$ aspect-tuned-adm verify

Verification succeeded, current system settings match the preset profile.
See Aspect-TuneD log file ('/var/log/aspect-tuned/aspect-tuned.log') for details.
----

[role="_additional-resources"]
.Additional resources
* `aspect-tuned.conf(5)` man page
