= About this documentation

This directory contains source files of Aspect-TuneD documentation intended for system administrators.

== Building the source

The documentation is written in the *AsciiDoc* markup language. To build it, install the link:https://asciidoctor.org/[asciidoctor] utility and use it to convert the master file:

----
$ asciidoctor doc/aspect-tuned-documentation/master.adoc
----

This generates the `master.html` file, which you can open with your web browser.

== Structure

The `master.adoc` file is the main entry point for the documentation. It _includes_ (or, imports, loads) _assembly_ files from the `assemblies/` directory, which represent user stories. These assembly files then include _modules_ located in `modules/performance/`. Modules are reusable sections of content representing a concept, a procedure, or a reference.

== Naming conventions

Use the following naming conventions when referring to Aspect-TuneD and its components in the documentation:

* "the *Aspect-TuneD* application", referring to the complete set of software, including executables, profiles, scripts, documentation, artwork, etc. Written as `the \*Aspect-TuneD* application` in AsciiDoc, because application names are in bold text.

* "the Aspect-TuneD project", referring to the developers and contributors, the web pages, repositories, planning, etc.

* "the `aspect-tuned` service", referring to the `aspect-tuned.service` systemd unit and the `aspect-tuned` executable

* "the `aspect-tuned-adm` utility", referring to the `aspect-tuned-adm` executable

* "the `aspect-tuned` and `aspect-tuned-adm` commands", referring to the text typed into the terminal to run components of Aspect-TuneD

This is consistent with other naming schemes. For example, consider "the Firefox application" vs. "the `firefox` command".
